# Generated by Django 4.1.13 on 2025-05-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websitebuilder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="website",
            name="hi",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
