# Generated by Django 4.1.13 on 2025-05-01 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("websitebuilder", "0002_website_hi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="website",
            name="hi",
        ),
    ]
